package: gloebals
version: '0.1-alpha'
author: 'FriendsOfREDAXO'
supportpage: https://github.com/FriendsOfREDAXO/gloebals

page:
    title: translate:navigation
    perm: gloebals[]
    pjax: false
    icon: rex-icon rex-icon-template
    subpages:
        tra: lala

requires:
    packages:
        structure/content: '>=2.1.0'
    redaxo: ^5.2.0

installer_ignore:
    - node_modules
